# Generated by Django 5.2.4 on 2025-07-22 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='email',
            field=models.EmailField(blank=True, help_text='Endereço de e-mail do professor', max_length=100, verbose_name='E-mail'),
        ),
        migrations.AddField(
            model_name='professor',
            name='especialidade',
            field=models.CharField(blank=True, help_text='Área de especialidade ou formação principal', max_length=100, verbose_name='Especialidade'),
        ),
        migrations.AddField(
            model_name='professor',
            name='telefone',
            field=models.CharField(blank=True, help_text='Telefone de contato do professor', max_length=20, verbose_name='Telefone'),
        ),
    ]
