# Generated by Django 5.2.4 on 2025-07-22 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_professor_email_professor_especialidade_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='preferenciaprofessor',
            options={'ordering': ['professor__nome_completo', 'dia_semana', 'turno'], 'verbose_name': 'Preferência do Professor', 'verbose_name_plural': 'Preferências dos Professores'},
        ),
        migrations.AlterUniqueTogether(
            name='preferenciaprofessor',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='preferenciaprofessor',
            name='disciplina',
            field=models.ForeignKey(blank=True, help_text='Disciplina específica (deixe vazio para qualquer disciplina)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='preferencias_professores', to='core.disciplina', verbose_name='Disciplina'),
        ),
        migrations.AlterField(
            model_name='preferenciaprofessor',
            name='dia_semana',
            field=models.IntegerField(blank=True, choices=[(0, 'Segunda-feira'), (1, 'Terça-feira'), (2, 'Quarta-feira'), (3, 'Quinta-feira'), (4, 'Sexta-feira'), (5, 'Sábado'), (6, 'Domingo')], help_text='Dia da semana específico (deixe vazio para qualquer dia)', null=True, verbose_name='Dia da Semana'),
        ),
        migrations.AlterField(
            model_name='preferenciaprofessor',
            name='observacoes',
            field=models.TextField(blank=True, help_text='Observações adicionais sobre esta preferência', verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='preferenciaprofessor',
            name='turno',
            field=models.CharField(blank=True, choices=[('manha', 'Manhã'), ('tarde', 'Tarde'), ('noite', 'Noite')], help_text='Turno específico (deixe vazio para qualquer turno)', max_length=10, verbose_name='Turno'),
        ),
        migrations.RemoveField(
            model_name='preferenciaprofessor',
            name='disponivel',
        ),
        migrations.RemoveField(
            model_name='preferenciaprofessor',
            name='preferencial',
        ),
    ]
