# Generated by Django 5.2.4 on 2025-07-23 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_preferenciaprofessor_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferenciaprofessor',
            name='disponivel',
            field=models.BooleanField(default=True, help_text='Se o professor está disponível neste horário/turno/dia', verbose_name='Disponível'),
        ),
        migrations.AddField(
            model_name='preferenciaprofessor',
            name='preferencial',
            field=models.BooleanField(default=False, help_text='Se este é um horário/turno/dia preferencial para o professor', verbose_name='Preferencial'),
        ),
        migrations.AddField(
            model_name='preferenciaprofessor',
            name='prioridade',
            field=models.IntegerField(choices=[(1, 'Baixa'), (2, 'Média'), (3, 'Normal'), (4, 'Alta'), (5, 'Crítica')], default=3, help_text='Nível de prioridade desta preferência (1=Baixa, 5=Crítica)', verbose_name='Prioridade'),
        ),
    ]
