# Generated by Django 5.2.4 on 2025-07-23 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_preferenciaprofessor_disponivel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='turno_turma',
            field=models.CharField(choices=[('matutino', 'Matutino (Manhã)'), ('vespertino', 'Vespertino (Tarde)'), ('noturno', 'Noturno (Noite)'), ('integral', 'Integral (Manhã e Tarde)'), ('flexivel', 'Flexível (Qualquer Turno)')], default='flexivel', help_text='Turno específico em que a turma estuda', max_length=15, verbose_name='Turno da Turma'),
        ),
        migrations.CreateModel(
            name='BloqueioTemporario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField(help_text='Data de início do bloqueio', verbose_name='Data de Início')),
                ('data_fim', models.DateField(help_text='Data de fim do bloqueio (deixe igual ao início para um dia específico)', verbose_name='Data de Fim')),
                ('turno', models.CharField(blank=True, choices=[('manha', 'Manhã'), ('tarde', 'Tarde'), ('noite', 'Noite')], help_text='Turno específico do bloqueio (deixe vazio para o dia todo)', max_length=10, verbose_name='Turno')),
                ('tipo_bloqueio', models.CharField(choices=[('falta', 'Falta/Ausência'), ('licenca', 'Licença'), ('reuniao', 'Reunião'), ('capacitacao', 'Capacitação/Curso'), ('pessoal', 'Motivo Pessoal'), ('outros', 'Outros')], default='falta', help_text='Motivo do bloqueio', max_length=20, verbose_name='Tipo de Bloqueio')),
                ('motivo', models.TextField(blank=True, help_text='Descrição detalhada do motivo do bloqueio', verbose_name='Motivo/Observações')),
                ('recorrente', models.BooleanField(default=False, help_text='Se este bloqueio se repete semanalmente (ex: toda quarta-feira)', verbose_name='Recorrente')),
                ('ativo', models.BooleanField(default=True, help_text='Se o bloqueio está ativo', verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloqueios', to='core.professor', verbose_name='Professor')),
            ],
            options={
                'verbose_name': 'Bloqueio Temporário',
                'verbose_name_plural': 'Bloqueios Temporários',
                'ordering': ['data_inicio', 'professor__nome_completo'],
            },
        ),
    ]
